# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Just In Thought
tagline: Tech, life, and random musings
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Tech, life, and random musings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://justinjao.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  justinjao
categories_path: "/categories"
tags_path: "/tags"
permalink: none

# Build settings

# removed a default gem theme because I'm using Monophase as a regular theme,
# as per instructions here: https://jekyllrb.com/docs/themes/#converting-gem-based-themes-to-regular-themes

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-sitemap
  - jemoji


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
